version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
      - cd bin/Debug/netcoreapp2.0/
      - zip -r9 $CODEBUILD_SRC_DIR/dotnet-core-app.zip
artifacts:
  files:
    - dotnet-core-app.zip
    - aws-windows-deployment-manifest.json
  discard-paths: yes
